title: John Doe # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I have 10+ years of experience, combined, in Data Analytics, and B2B Sales. 
  Feel free to reach me at <a href="https://www.linkedin.com/in/fernandodoreto/ target="_blank"">LinkedIn</a>
  <br>
  Here youâ€™re going to find: My latest personal projects and
  Free content recommendation to learn and apply Data Science.
   
  
theme: jekyll-theme-minimal
google_analytics: 
